# Generated by Django 3.2 on 2021-04-21 03:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mblogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 21, 3, 13, 2, 15162, tzinfo=utc)),
        ),
    ]
